import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Block1 from '@/src/contents/Block1'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* this is nav  */}
      <nav className='bg-emerald-400'>
        <p className='text-white text-center py-2'>Todo application</p>
      </nav>
      <Block1/>
    </>
  )
}
